### ISSUE TITLE
Submit the paper to a journal

### ISSUE THREAD

**Issue by leouieda** [compgeolab/eql-gradient-boosted#136]
## Information

- Journal name: Geophysical Journal International
- Journal guidelines for authors: https://academic.oup.com/gji/pages/General_Instructions
- Supplementary material DOI: https://doi.org/10.6084/m9.figshare.13604360

This is the standard EarthArXiv disclaimer for a preprint:

```
\noindent
\textbf{Disclaimer:}
This is a non-peer reviewed preprint submitted to EarthArXiv.
It is currently under review at \textit{insert-journal}.
```

## Checklist

- [x] Reserve a DOI on [figshare](https://figshare.com/) or [Zenodo](https://zenodo.org/) for the supplementary material (zip archive of this repository). Paste the DOI at the top of this issue.
- [x] Add the _supplementary DOI_ to the manuscript
- [x] Make a cover letter for the editor. Include a short summary, suggested reviewers, and contributions by student authors
- [x] Submit the paper to the Journal
- [x] Submit the preprint to [EarthArXiv](https://eartharxiv.org/) 
- [x] Add the _preprint DOI_ to the `README.md`
- [x] Make a release on GitHub
- [x] Upload the `.zip` version of the repository to figshare or Zenodo and publish it
- [x] Add the preprint to the CompGeoLab (and your personal) website
- [x] Tell people about your preprint on social media (include a figure and maybe a thread with the main results)

**Comment by leouieda** [comment]
@santisoler I'm thinking that we could archive the repository already now and update it after publication. The only issue is if the paper is rejected and we want to make this private again. But we'd still have the preprint there anyway so it wouldn't matter. What do you think?

**Comment by santisoler** [comment]
> @santisoler I'm thinking that we could archive the repository already now and update it after publication. The only issue is if the paper is rejected and we want to make this private again. But we'd still have the preprint there anyway so it wouldn't matter. What do you think?

Since the preprint is already out, I wouldn't make this repo private again I think... so I'm ok for archiving the repo after #144 is merged.
